CREATE TABLE USU_USUARIO(
USU_ID			INT(13),
USU_SENHA		VARCHAR(300),
USU_NOME		VARCHAR(50),
USU_EMAIL		VARCHAR(30),
CONSTRAINT USU_PK PRIMARY KEY (USU_ID),
CONSTRAINT USU_UK UNIQUE (USU_EMAIL));

CREATE TABLE QUE_QUESTAO(
QUE_ID			INT(13),
QUE_PERGUNTA	VARCHAR(300),
CONSTRAINT QUE_ID PRIMARY KEY (QUE_ID));

CREATE TABLE OP_OPCAO(
OP_ID			INT(13),
OP_ALTERNATIVA	INT(4),
OP_CONSUMO		INT(4),
QUE_ID			INT(13),
CONSTRAINT OP_PK PRIMARY KEY (OP_ID),
CONSTRAINT OP_FK FOREIGN KEY (QUE_ID) REFERENCES QUE_QUESTAO(QUE_ID));

